env:
  global:
    - TERM=dumb
notifications:
  email: false
git:
  quiet: true
  depth: false
language: python
python: 3.8
node_js: lts/*
jdk: openjdk11
services: docker
addons:
  apt:
    update: false
    packages:
      - curl
      - docker-ce
install: true
before_install:
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash
    stop_any 5672 15672 3000 5000 8000 8080 80
  - |
    export PATH=$HOME/.local/bin:$PATH
    python -m pip install --upgrade pip setuptools pyopenssl
    python -m pip install --upgrade httpie docker-compose
jobs:
  include:
    - stage: test
      name: tests
      before_script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw -f rabbitmq docker:build docker:start
        - cd $TRAVIS_BUILD_DIR && ./mvnw
        - bash $TRAVIS_BUILD_DIR/source-output-app/target/*.jar &
        - bash $TRAVIS_BUILD_DIR/processor-transforming-app/target/*.jar &
        - bash $TRAVIS_BUILD_DIR/sink-input-app/target/*.jar &
        - wait_for 8081 8082 8083
      script:
        - sleep 15s
      after_script:
        - http post :8081/actuator/shutdown
        - http post :8082/actuator/shutdown
        - http post :8083/actuator/shutdown
        - cd $TRAVIS_BUILD_DIR && ./mvnw -f rabbitmq docker:stop docker:remove
cache:
  directories:
    - ~/.m2
    - ~/.docker
  packages: true
  pip: true
